# This config of the Flectone plugin
# Should not be deleted <prefix>, <player>, <message>
# You can change true to false and vice versa
# The rest can be edited/deleted/done as you please
# ________  _____     ________    ______  _________    ___   ____  _____  ________  
#|_   __  ||_   _|   |_   __  | .' ___  ||  _   _  | .'   `.|_   \|_   _||_   __  | 
#  | |_ \_|  | |       | |_ \_|/ .'   \_||_/ | | \_|/  .-.  \ |   \ | |    | |_ \_| 
#  |  _|     | |   _   |  _| _ | |           | |    | |   | | | |\ \| |    |  _| _  
# _| |_     _| |__/ | _| |__/ |\ `.___.'\   _| |_   \  `-'  /_| |_\   |_  _| |__/ | 
#|_____|   |________||________| `.____ .'  |_____|   `.___.'|_____|\____||________|                                                                                   
#   ______  ____  ____       _     _________  
# .' ___  ||_   ||   _|     / \   |  _   _  | 
#/ .'   \_|  | |__| |      / _ \  |_/ | | \_| 
#| |         |  __  |     / ___ \     | |     
#\ `.___.'\ _| |  | |_  _/ /   \ \_  _| |_    
# `.____ .'|____||____||____| |____||_____|   
#                                               
#At the moment there are only 2 language formats: ru_RU and en_US
language: en_US 

#Actions on join
player_action:
  on_join:  
  
#If true, op is issued when logging into the server
    give_op: false

#There are only 3 game modes: CREATIVE, ADVENTURE, SURVIVAL
#If you want to turn off or not give everyone the same game mode, leave the field blank,
#Like this: gamemode: ""
    gamemode: "SURVIVAL"



#Chat message format
chat:
  format: "&b<prefix> &f<player> &b» &f<message>"
  local:
#Local chat prefix
    prefix: "[L]"

#Range on which the local chat works
    range: 100

  global:
#Global chat prefix
    prefix: "[G]"

#Global chat condition (at the beginning of the message)
    condition: "!"
    
    
#Prefix to hover over to remove a player from the ignorelist
ignorelist:
  prefix: "&c[x] "



#Sound accompaniment of all actions
#True - enable, false - disable
#Success - sound on execution, fail - sound on error
#You can set any sound, I recommend that you first select it from the /playsound command
sound:
  on_join:
    enable: true
    success: "minecraft:block.note_block.bell"
  tell:
    enable: true
    success: "minecraft:block.note_block.iron_xylophone"
    fail: "minecraft:block.note_block.bass"
  reply:
    enable: true
    fail: "minecraft:block.note_block.bass"
  ignore: 
    enable: true
    fail: "minecraft:block.note_block.bass"
  ignorelist:
    enable: true
    fail: "minecraft:block.note_block.bass"
  me:
    enable: true
  action:   
    enable: true
    success: "minecraft:block.note_block.iron_xylophone"
    fail: "minecraft:block.note_block.bass"
  reload:
    enable: true
    success: "minecraft:block.note_block.iron_xylophone"